title: Portfolio of Rachana   
description: resume card of Rachana Vankayalapati.
sitename: Your Website
baseurl: '/RachanaV'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
